jobs:
  - name: Clean [${service_branch}] hardening
    install_version: ${service_branch}
    template: templates/rabbitmq-service/rabbitmq_clean_sc_hardening.yml
    sequence: install
    restricted: true
    artifact_name: Clean_CURRENT_Hardening
